[package]
name = "dlmalloc"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
doctest = false
test = false

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", default-features = false }

[dev-dependencies]
rand = "0.3"

# [build-dependencies]
# cc = { version = "1.0", optional = true }
#
# [features]
# c = ["cc"]
